#!/usr/bin/env node
/**
 * Generates /seed/*.json and /supabase/seed_wishlist.sql
 * Run: node seed/build.mjs
 */
import { writeFileSync, mkdirSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'
import { MOVIES } from './data/movies.js'
import { CHEESES } from './data/cheeses.js'
import { COUNTRIES } from './data/countries.js'
import { BOOKS } from './data/books.js'
import { LONDON } from './data/london.js'
import { SUMMER_JOYS } from './data/summer-joys.js'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = join(__dirname, '..')

const COLLECTIONS = [
  {
    slug: '100-movies',
    title: '100 Films Before You Die',
    description: 'Essential cinema — from silent classics to modern masterpieces.',
    emoji: '🎬',
    cover_style: 'ink-slate',
    default_tags: {
      time_needed: 'few_hours',
      cost: 'free',
      company: 'any',
      setting: 'home',
      seasons: ['any'],
      topic_tags: ['film'],
    },
    items: MOVIES,
  },
  {
    slug: 'cheese-atlas',
    title: 'The World Cheese Atlas',
    description: 'Sixty cheeses worth knowing, tasting, and remembering.',
    emoji: '🧀',
    cover_style: 'ochre-warm',
    default_tags: {
      time_needed: '30min',
      cost: 'cheap',
      company: 'any',
      setting: 'home',
      seasons: ['any'],
      topic_tags: ['cheese', 'food'],
    },
    items: CHEESES,
  },
  {
    slug: 'countries',
    title: '195 Countries',
    description: 'Every nation on earth — a lifetime of horizons.',
    emoji: '✈️',
    cover_style: 'sage-mist',
    default_tags: {
      time_needed: 'trip',
      cost: 'splurge',
      company: 'any',
      setting: 'travel',
      seasons: ['any'],
      topic_tags: ['travel'],
    },
    items: COUNTRIES,
  },
  {
    slug: '100-books',
    title: '100 Books Before You Die',
    description: 'The shelf that shapes a reader.',
    emoji: '📚',
    cover_style: 'dusty-rose',
    default_tags: {
      time_needed: 'few_hours',
      cost: 'cheap',
      company: 'solo',
      setting: 'home',
      seasons: ['any'],
      topic_tags: ['reading'],
    },
    items: BOOKS,
  },
  {
    slug: 'london-100',
    title: 'London: 100 Things',
    description: 'A hundred reasons this city keeps giving.',
    emoji: '🚇',
    cover_style: 'terracotta',
    default_tags: {
      time_needed: 'few_hours',
      cost: 'cheap',
      company: 'any',
      setting: 'outdoors',
      seasons: ['any'],
      topic_tags: ['london'],
    },
    items: LONDON,
  },
  {
    slug: 'summer-joys',
    title: 'Silly Summer Things',
    description: 'Fifty small pleasures that taste like sunshine.',
    emoji: '☀️',
    cover_style: 'honey-glow',
    default_tags: {
      time_needed: '30min',
      cost: 'free',
      company: 'any',
      setting: 'outdoors',
      seasons: ['summer'],
      topic_tags: ['summer'],
    },
    items: SUMMER_JOYS,
  },
]

function sqlEscape(s) {
  return s.replace(/'/g, "''")
}

function jsonSql(obj) {
  return `'${sqlEscape(JSON.stringify(obj))}'::jsonb`
}

function categoryForSlug(slug) {
  switch (slug) {
    case '100-movies':
    case '100-books':
      return 'watch_read'
    case 'cheese-atlas':
      return 'taste'
    case 'countries':
      return 'go'
    case 'london-100':
      return 'london'
    case 'summer-joys':
      return 'micro_joys'
    default:
      return 'someday'
  }
}

function textArraySql(arr) {
  if (!arr?.length) return `ARRAY[]::text[]`
  return `ARRAY[${arr.map((s) => `'${sqlEscape(s)}'`).join(', ')}]::text[]`
}

function tagsSql(tags) {
  return [
    `'${sqlEscape(tags.time_needed)}'::wishlist_time_needed`,
    `'${sqlEscape(tags.cost)}'::wishlist_cost_level`,
    `'${sqlEscape(tags.company)}'::wishlist_company_type`,
    `'${sqlEscape(tags.setting)}'::wishlist_setting_type`,
    textArraySql(tags.seasons ?? []),
    textArraySql(tags.topic_tags ?? []),
  ].join(', ')
}

function buildSql(collections) {
  const lines = [
    '-- Idempotent wishlist seed — INSERT/UPSERT into wishlist_* tables only',
    '-- Generated by seed/build.mjs',
    '',
  ]

  let sortOrder = 0
  for (const col of collections) {
    sortOrder += 1
    const category = categoryForSlug(col.slug)
    lines.push(`-- List: ${col.slug}`)
    lines.push(
      `INSERT INTO wishlist_lists (slug, title, emoji, is_seeded, sort_order)`,
    )
    lines.push(`VALUES (`)
    lines.push(`  '${sqlEscape(col.slug)}',`)
    lines.push(`  '${sqlEscape(col.title)}',`)
    lines.push(`  '${sqlEscape(col.emoji)}',`)
    lines.push(`  true,`)
    lines.push(`  ${sortOrder}`)
    lines.push(`)`)
    lines.push(`ON CONFLICT (slug) WHERE slug IS NOT NULL DO UPDATE SET`)
    lines.push(`  title = EXCLUDED.title,`)
    lines.push(`  emoji = EXCLUDED.emoji,`)
    lines.push(`  is_seeded = EXCLUDED.is_seeded,`)
    lines.push(`  sort_order = EXCLUDED.sort_order;`)
    lines.push('')

    for (const item of col.items) {
      const seedKey = `${col.slug}:${item.key}`
      const tags = item.default_tags ?? col.default_tags
      lines.push(
        `INSERT INTO wishlist_items (list_id, title, note, category, is_seeded, source_seed_key, sort_order, time_needed, cost, company, setting, seasons, topic_tags, status)`,
      )
      lines.push(`SELECT l.id, '${sqlEscape(item.title)}',`)
      lines.push(item.subtitle ? `  '${sqlEscape(item.subtitle)}',` : `  NULL,`)
      lines.push(`  '${category}'::wishlist_category,`)
      lines.push(`  true,`)
      lines.push(`  '${sqlEscape(seedKey)}',`)
      lines.push(`  ${item.sort_order},`)
      lines.push(`  ${tagsSql(tags)},`)
      lines.push(`  'open'::wishlist_item_status`)
      lines.push(`FROM wishlist_lists l WHERE l.slug = '${sqlEscape(col.slug)}'`)
      lines.push(
        `ON CONFLICT (list_id, source_seed_key) WHERE source_seed_key IS NOT NULL AND is_seeded = true DO UPDATE SET`,
      )
      lines.push(`  title = EXCLUDED.title,`)
      lines.push(`  note = EXCLUDED.note,`)
      lines.push(`  category = EXCLUDED.category,`)
      lines.push(`  sort_order = EXCLUDED.sort_order,`)
      lines.push(`  time_needed = EXCLUDED.time_needed,`)
      lines.push(`  cost = EXCLUDED.cost,`)
      lines.push(`  company = EXCLUDED.company,`)
      lines.push(`  setting = EXCLUDED.setting,`)
      lines.push(`  seasons = EXCLUDED.seasons,`)
      lines.push(`  topic_tags = EXCLUDED.topic_tags;`)
      lines.push('')
    }
  }

  lines.push('-- Verify counts')
  lines.push(
    `SELECT l.slug, (SELECT COUNT(*) FROM wishlist_items i WHERE i.list_id = l.id AND i.is_seeded = true) AS item_count`,
  )
  lines.push(`FROM wishlist_lists l WHERE l.is_seeded = true ORDER BY l.slug;`)

  return lines.join('\n')
}

mkdirSync(join(root, 'seed'), { recursive: true })

const summary = []

for (const col of COLLECTIONS) {
  const out = {
    slug: col.slug,
    title: col.title,
    description: col.description,
    emoji: col.emoji,
    cover_style: col.cover_style,
    default_tags: col.default_tags,
    items: col.items.map(({ key, title, subtitle, meta, default_tags, sort_order }) => ({
      key,
      title,
      subtitle,
      meta,
      default_tags,
      sort_order,
    })),
  }
  writeFileSync(join(root, 'seed', `${col.slug}.json`), JSON.stringify(out, null, 2))
  summary.push({ slug: col.slug, count: col.items.length })
}

writeFileSync(join(root, 'supabase', 'seed_wishlist.sql'), buildSql(COLLECTIONS))

console.log('Seed files generated:')
for (const s of summary) {
  console.log(`  ${s.slug}: ${s.count} items`)
}
console.log(`  Total items: ${summary.reduce((a, b) => a + b.count, 0)}`)
console.log('SQL: supabase/seed_wishlist.sql')
