#!/usr/bin/env node
import { writeFileSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const dir = join(dirname(fileURLToPath(import.meta.url)), 'data')

const MOVIE_RAW = [
  ['Citizen Kane', 1941, 'Orson Welles'],
  ['Casablanca', 1942, 'Michael Curtiz'],
  ['The Godfather', 1972, 'Francis Ford Coppola'],
  ['The Godfather Part II', 1974, 'Francis Ford Coppola'],
  ['Singin\' in the Rain', 1952, 'Gene Kelly'],
  ['Schindler\'s List', 1993, 'Steven Spielberg'],
  ['Vertigo', 1958, 'Alfred Hitchcock'],
  ['Psycho', 1960, 'Alfred Hitchcock'],
  ['Sunset Boulevard', 1950, 'Billy Wilder'],
  ['Lawrence of Arabia', 1962, 'David Lean'],
  ['The Wizard of Oz', 1939, 'Victor Fleming'],
  ['The Searchers', 1956, 'John Ford'],
  ['2001: A Space Odyssey', 1968, 'Stanley Kubrick'],
  ['Apocalypse Now', 1979, 'Francis Ford Coppola'],
  ['Raging Bull', 1980, 'Martin Scorsese'],
  ['Tokyo Story', 1953, 'Yasujiro Ozu'],
  ['City Lights', 1931, 'Charlie Chaplin'],
  ['The General', 1926, 'Buster Keaton'],
  ['Some Like It Hot', 1959, 'Billy Wilder'],
  ['The Shawshank Redemption', 1994, 'Frank Darabont'],
  ['Pulp Fiction', 1994, 'Quentin Tarantino'],
  ['Goodfellas', 1990, 'Martin Scorsese'],
  ['The Dark Knight', 2008, 'Christopher Nolan'],
  ['Inception', 2010, 'Christopher Nolan'],
  ['Parasite', 2019, 'Bong Joon-ho'],
  ['Spirited Away', 2001, 'Hayao Miyazaki'],
  ['Seven Samurai', 1954, 'Akira Kurosawa'],
  ['Rashomon', 1950, 'Akira Kurosawa'],
  ['Yojimbo', 1961, 'Akira Kurosawa'],
  ['Ikiru', 1952, 'Akira Kurosawa'],
  ['La Dolce Vita', 1960, 'Federico Fellini'],
  ['8½', 1963, 'Federico Fellini'],
  ['Bicycle Thieves', 1948, 'Vittorio De Sica'],
  ['The 400 Blows', 1959, 'François Truffaut'],
  ['Breathless', 1960, 'Jean-Luc Godard'],
  ['Amélie', 2001, 'Jean-Pierre Jeunet'],
  ['The Rules of the Game', 1939, 'Jean Renoir'],
  ['Children of Paradise', 1945, 'Marcel Carné'],
  ['Metropolis', 1927, 'Fritz Lang'],
  ['M', 1931, 'Fritz Lang'],
  ['Das Boot', 1981, 'Wolfgang Petersen'],
  ['Run Lola Run', 1998, 'Tom Tykwer'],
  ['Pan\'s Labyrinth', 2006, 'Guillermo del Toro'],
  ['All About My Mother', 1999, 'Pedro Almodóvar'],
  ['Talk to Her', 2002, 'Pedro Almodóvar'],
  ['Amores Perros', 2000, 'Alejandro González Iñárritu'],
  ['City of God', 2002, 'Fernando Meirelles'],
  ['Central Station', 1998, 'Walter Salles'],
  ['Oldboy', 2003, 'Park Chan-wook'],
  ['In the Mood for Love', 2000, 'Wong Kar-wai'],
  ['Chungking Express', 1994, 'Wong Kar-wai'],
  ['Crouching Tiger, Hidden Dragon', 2000, 'Ang Lee'],
  ['Farewell My Concubine', 1993, 'Chen Kaige'],
  ['Raise the Red Lantern', 1991, 'Zhang Yimou'],
  ['The Battle of Algiers', 1966, 'Gillo Pontecorvo'],
  ['A Separation', 2011, 'Asghar Farhadi'],
  ['Close-Up', 1990, 'Abbas Kiarostami'],
  ['The Lives of Others', 2006, 'Florian Henckel von Donnersmarck'],
  ['The Piano', 1993, 'Jane Campion'],
  ['Once Were Warriors', 1994, 'Lee Tamahori'],
  ['Whale Rider', 2002, 'Niki Caro'],
  ['The Piano Teacher', 2001, 'Michael Haneke'],
  ['Amour', 2012, 'Michael Haneke'],
  ['The Seventh Seal', 1957, 'Ingmar Bergman'],
  ['Persona', 1966, 'Ingmar Bergman'],
  ['Wild Strawberries', 1957, 'Ingmar Bergman'],
  ['Fanny and Alexander', 1982, 'Ingmar Bergman'],
  ['The Sacrifice', 1986, 'Andrei Tarkovsky'],
  ['Stalker', 1979, 'Andrei Tarkovsky'],
  ['Solaris', 1972, 'Andrei Tarkovsky'],
  ['Mirror', 1975, 'Andrei Tarkovsky'],
  ['Come and See', 1985, 'Elem Klimov'],
  ['Grave of the Fireflies', 1988, 'Isao Takahata'],
  ['My Neighbor Totoro', 1988, 'Hayao Miyazaki'],
  ['Princess Mononoke', 1997, 'Hayao Miyazaki'],
  ['Howl\'s Moving Castle', 2004, 'Hayao Miyazaki'],
  ['Perfect Blue', 1997, 'Satoshi Kon'],
  ['Akira', 1988, 'Katsuhiro Otomo'],
  ['Ghost in the Shell', 1995, 'Mamoru Oshii'],
  ['Your Name', 2016, 'Makoto Shinkai'],
  ['The Matrix', 1999, 'The Wachowskis'],
  ['Blade Runner', 1982, 'Ridley Scott'],
  ['Alien', 1979, 'Ridley Scott'],
  ['Mad Max: Fury Road', 2015, 'George Miller'],
  ['Terminator 2', 1991, 'James Cameron'],
  ['Titanic', 1997, 'James Cameron'],
  ['E.T.', 1982, 'Steven Spielberg'],
  ['Jaws', 1975, 'Steven Spielberg'],
  ['Close Encounters', 1977, 'Steven Spielberg'],
  ['Raiders of the Lost Ark', 1981, 'Steven Spielberg'],
  ['Jurassic Park', 1993, 'Steven Spielberg'],
  ['Saving Private Ryan', 1998, 'Steven Spielberg'],
  ['The Shining', 1980, 'Stanley Kubrick'],
  ['A Clockwork Orange', 1971, 'Stanley Kubrick'],
  ['Dr. Strangelove', 1964, 'Stanley Kubrick'],
  ['Full Metal Jacket', 1987, 'Stanley Kubrick'],
  ['Barry Lyndon', 1975, 'Stanley Kubrick'],
  ['Paths of Glory', 1957, 'Stanley Kubrick'],
  ['Taxi Driver', 1976, 'Martin Scorsese'],
  ['The Departed', 2006, 'Martin Scorsese'],
  ['Silence', 2016, 'Martin Scorsese'],
  ['There Will Be Blood', 2007, 'Paul Thomas Anderson'],
  ['Magnolia', 1999, 'Paul Thomas Anderson'],
  ['Boogie Nights', 1997, 'Paul Thomas Anderson'],
  ['No Country for Old Men', 2007, 'Joel & Ethan Coen'],
  ['Fargo', 1996, 'Joel & Ethan Coen'],
  ['The Big Lebowski', 1998, 'Joel & Ethan Coen'],
  ['Inside Llewyn Davis', 2013, 'Joel & Ethan Coen'],
  ['Moonlight', 2016, 'Barry Jenkins'],
  ['Lady Bird', 2017, 'Greta Gerwig'],
  ['Little Women', 2019, 'Greta Gerwig'],
  ['Nomadland', 2020, 'Chloé Zhao'],
  ['The Power of the Dog', 2021, 'Jane Campion'],
  ['Get Out', 2017, 'Jordan Peele'],
  ['Do the Right Thing', 1989, 'Spike Lee'],
  ['Malcolm X', 1992, 'Spike Lee'],
  ['Boyhood', 2014, 'Richard Linklater'],
  ['Before Sunrise', 1995, 'Richard Linklater'],
  ['Lost in Translation', 2003, 'Sofia Coppola'],
  ['Her', 2013, 'Spike Jonze'],
  ['Eternal Sunshine', 2004, 'Michel Gondry'],
  ['The Grand Budapest Hotel', 2014, 'Wes Anderson'],
  ['Moonrise Kingdom', 2012, 'Wes Anderson'],
  ['The Royal Tenenbaums', 2001, 'Wes Anderson'],
  ['Annie Hall', 1977, 'Woody Allen'],
  ['Manhattan', 1979, 'Woody Allen'],
  ['Blue Velvet', 1986, 'David Lynch'],
  ['Mulholland Drive', 2001, 'David Lynch'],
  ['Eraserhead', 1977, 'David Lynch'],
  ['Rear Window', 1954, 'Alfred Hitchcock'],
  ['North by Northwest', 1959, 'Alfred Hitchcock'],
  ['The Birds', 1963, 'Alfred Hitchcock'],
  ['Notorious', 1946, 'Alfred Hitchcock'],
  ['It\'s a Wonderful Life', 1946, 'Frank Capra'],
  ['Modern Times', 1936, 'Charlie Chaplin'],
  ['The Gold Rush', 1925, 'Charlie Chaplin'],
  ['Nosferatu', 1922, 'F.W. Murnau'],
  ['Sunrise', 1927, 'F.W. Murnau'],
  ['The Passion of Joan of Arc', 1928, 'Carl Theodor Dreyer'],
  ['Battleship Potemkin', 1925, 'Sergei Eisenstein'],
  ['Man with a Movie Camera', 1929, 'Dziga Vertov'],
  ['La Haine', 1995, 'Mathieu Kassovitz'],
  ['Portrait of a Lady on Fire', 2019, 'Céline Sciamma'],
  ['The Handmaiden', 2016, 'Park Chan-wook'],
  ['Shoplifters', 2018, 'Hirokazu Kore-eda'],
  ['Drive My Car', 2021, 'Ryusuke Hamaguchi'],
  ['Past Lives', 2023, 'Céline Song'],
  ['Everything Everywhere All at Once', 2022, 'Daniels'],
  ['The Zone of Interest', 2023, 'Jonathan Glazer'],
  ['Oppenheimer', 2023, 'Christopher Nolan'],
  ['Killers of the Flower Moon', 2023, 'Martin Scorsese'],
  ['Anatomy of a Fall', 2023, 'Justine Triet'],
  ['The Holdovers', 2023, 'Alexander Payne'],
  ['Aftersun', 2022, 'Charlotte Wells'],
  ['The Worst Person in the World', 2021, 'Joachim Trier'],
  ['Roma', 2018, 'Alfonso Cuarón'],
  ['Gravity', 2013, 'Alfonso Cuarón'],
  ['Children of Men', 2006, 'Alfonso Cuarón'],
  ['Y Tu Mamá También', 2001, 'Alfonso Cuarón'],
  ['Pan\'s Labyrinth', 2006, 'Guillermo del Toro'],
  ['The Shape of Water', 2017, 'Guillermo del Toro'],
  ['Babel', 2006, 'Alejandro González Iñárritu'],
  ['Birdman', 2014, 'Alejandro González Iñárritu'],
  ['The Revenant', 2015, 'Alejandro González Iñárritu'],
  ['Whiplash', 2014, 'Damien Chazelle'],
  ['La La Land', 2016, 'Damien Chazelle'],
  ['The Social Network', 2010, 'David Fincher'],
  ['Fight Club', 1999, 'David Fincher'],
  ['Se7en', 1995, 'David Fincher'],
  ['Zodiac', 2007, 'David Fincher'],
  ['Gone Girl', 2014, 'David Fincher'],
  ['The Silence of the Lambs', 1991, 'Jonathan Demme'],
  ['One Flew Over the Cuckoo\'s Nest', 1975, 'Miloš Forman'],
  ['Network', 1976, 'Sidney Lumet'],
  ['12 Angry Men', 1957, 'Sidney Lumet'],
  ['Dog Day Afternoon', 1975, 'Sidney Lumet'],
  ['The Apartment', 1960, 'Billy Wilder'],
  ['Double Indemnity', 1944, 'Billy Wilder'],
  ['Witness for the Prosecution', 1957, 'Billy Wilder'],
  ['The Third Man', 1949, 'Carol Reed'],
  ['Brief Encounter', 1945, 'David Lean'],
  ['Kind Hearts and Coronets', 1949, 'Robert Hamer'],
  ['Trainspotting', 1996, 'Danny Boyle'],
  ['Slumdog Millionaire', 2008, 'Danny Boyle'],
  ['28 Days Later', 2002, 'Danny Boyle'],
  ['Shaun of the Dead', 2004, 'Edgar Wright'],
  ['Hot Fuzz', 2007, 'Edgar Wright'],
  ['The World\'s End', 2013, 'Edgar Wright'],
  ['Withnail & I', 1987, 'Bruce Robinson'],
  ['This Is England', 2006, 'Shane Meadows'],
  ['Atonement', 2007, 'Joe Wright'],
  ['Pride & Prejudice', 2005, 'Joe Wright'],
  ['The Remains of the Day', 1993, 'James Ivory'],
  ['Room with a View', 1985, 'James Ivory'],
  ['Call Me by Your Name', 2017, 'Luca Guadagnino'],
  ['Brokeback Mountain', 2005, 'Ang Lee'],
  ['Life of Pi', 2012, 'Ang Lee'],
  ['Sense and Sensibility', 1995, 'Ang Lee'],
  ['The Ice Storm', 1997, 'Ang Lee'],
  ['Memories of Murder', 2003, 'Bong Joon-ho'],
  ['Snowpiercer', 2013, 'Bong Joon-ho'],
  ['Burning', 2018, 'Lee Chang-dong'],
  ['Poetry', 2010, 'Lee Chang-dong'],
  ['Peppermint Candy', 1999, 'Lee Chang-dong'],
  ['Happy Together', 1997, 'Wong Kar-wai'],
  ['Days of Being Wild', 1990, 'Wong Kar-wai'],
  ['Fallen Angels', 1995, 'Wong Kar-wai'],
  ['Hero', 2002, 'Zhang Yimou'],
  ['House of Flying Daggers', 2004, 'Zhang Yimou'],
  ['In the Heat of the Sun', 1994, 'Jiang Wen'],
  ['Still Life', 2006, 'Jia Zhangke'],
  ['A Touch of Sin', 2013, 'Jia Zhangke'],
  ['Uncle Boonmee', 2010, 'Apichatpong Weerasethakul'],
  ['Tropical Malady', 2004, 'Apichatpong Weerasethakul'],
  ['Uncle Boonmee Who Can Recall His Past Lives', 2010, 'Apichatpong Weerasethakul'],
]

const BOOK_RAW = [
  ['Pride and Prejudice', 'Jane Austen', 1813],
  ['Jane Eyre', 'Charlotte Brontë', 1847],
  ['Wuthering Heights', 'Emily Brontë', 1847],
  ['Great Expectations', 'Charles Dickens', 1861],
  ['Bleak House', 'Charles Dickens', 1853],
  ['Middlemarch', 'George Eliot', 1871],
  ['Moby-Dick', 'Herman Melville', 1851],
  ['The Adventures of Huckleberry Finn', 'Mark Twain', 1884],
  ['The Great Gatsby', 'F. Scott Fitzgerald', 1925],
  ['To Kill a Mockingbird', 'Harper Lee', 1960],
  ['1984', 'George Orwell', 1949],
  ['Animal Farm', 'George Orwell', 1945],
  ['Brave New World', 'Aldous Huxley', 1932],
  ['Catch-22', 'Joseph Heller', 1961],
  ['Slaughterhouse-Five', 'Kurt Vonnegut', 1969],
  ['The Catcher in the Rye', 'J.D. Salinger', 1951],
  ['One Hundred Years of Solitude', 'Gabriel García Márquez', 1967],
  ['Love in the Time of Cholera', 'Gabriel García Márquez', 1985],
  ['The Master and Margarita', 'Mikhail Bulgakov', 1967],
  ['Crime and Punishment', 'Fyodor Dostoevsky', 1866],
  ['The Brothers Karamazov', 'Fyodor Dostoevsky', 1880],
  ['Anna Karenina', 'Leo Tolstoy', 1877],
  ['War and Peace', 'Leo Tolstoy', 1869],
  ['Madame Bovary', 'Gustave Flaubert', 1856],
  ['Les Misérables', 'Victor Hugo', 1862],
  ['The Count of Monte Cristo', 'Alexandre Dumas', 1844],
  ['Don Quixote', 'Miguel de Cervantes', 1605],
  ['The Odyssey', 'Homer', -800],
  ['The Iliad', 'Homer', -750],
  ['The Divine Comedy', 'Dante Alighieri', 1320],
  ['Hamlet', 'William Shakespeare', 1603],
  ['King Lear', 'William Shakespeare', 1606],
  ['Macbeth', 'William Shakespeare', 1606],
  ['The Tempest', 'William Shakespeare', 1611],
  ['Beloved', 'Toni Morrison', 1987],
  ['Song of Solomon', 'Toni Morrison', 1977],
  ['Invisible Man', 'Ralph Ellison', 1952],
  ['Their Eyes Were Watching God', 'Zora Neale Hurston', 1937],
  ['The Color Purple', 'Alice Walker', 1982],
  ['Things Fall Apart', 'Chinua Achebe', 1958],
  ['Half of a Yellow Sun', 'Chimamanda Ngozi Adichie', 2006],
  ['Americanah', 'Chimamanda Ngozi Adichie', 2013],
  ['The God of Small Things', 'Arundhati Roy', 1997],
  ['Midnight\'s Children', 'Salman Rushdie', 1981],
  ['The Satanic Verses', 'Salman Rushdie', 1988],
  ['A Suitable Boy', 'Vikram Seth', 1993],
  ['The White Tiger', 'Aravind Adiga', 2008],
  ['Life of Pi', 'Yann Martel', 2001],
  ['The Kite Runner', 'Khaled Hosseini', 2003],
  ['A Thousand Splendid Suns', 'Khaled Hosseini', 2007],
  ['Norwegian Wood', 'Haruki Murakami', 1987],
  ['Kafka on the Shore', 'Haruki Murakami', 2002],
  ['The Wind-Up Bird Chronicle', 'Haruki Murakami', 1994],
  ['Snow Country', 'Yasunari Kawabata', 1937],
  ['The Tale of Genji', 'Murasaki Shikibu', 1008],
  ['The Pillow Book', 'Sei Shōnagon', 1002],
  ['Waiting', 'Ha Jin', 1999],
  ['The Three-Body Problem', 'Liu Cixin', 2008],
  ['The Vegetarian', 'Han Kang', 2007],
  ['Pachinko', 'Min Jin Lee', 2017],
  ['The Sympathizer', 'Viet Thanh Nguyen', 2015],
  ['On Earth We\'re Briefly Gorgeous', 'Ocean Vuong', 2019],
  ['The Brief Wondrous Life of Oscar Wao', 'Junot Díaz', 2007],
  ['One Hundred Years of Solitude', 'Gabriel García Márquez', 1967],
  ['2666', 'Roberto Bolaño', 2004],
  ['The Savage Detectives', 'Roberto Bolaño', 1998],
  ['Ficciones', 'Jorge Luis Borges', 1944],
  ['Labyrinths', 'Jorge Luis Borges', 1962],
  ['Pedro Páramo', 'Juan Rulfo', 1955],
  ['The House of the Spirits', 'Isabel Allende', 1982],
  ['Blindness', 'José Saramago', 1995],
  ['The Year of the Death of Ricardo Reis', 'José Saramago', 1984],
  ['The Shadow of the Wind', 'Carlos Ruiz Zafón', 2001],
  ['The Name of the Rose', 'Umberto Eco', 1980],
  ['If on a winter\'s night a traveler', 'Italo Calvino', 1979],
  ['Invisible Cities', 'Italo Calvino', 1972],
  ['The Stranger', 'Albert Camus', 1942],
  ['The Plague', 'Albert Camus', 1947],
  ['Nausea', 'Jean-Paul Sartre', 1938],
  ['Swann\'s Way', 'Marcel Proust', 1913],
  ['Ulysses', 'James Joyce', 1922],
  ['A Portrait of the Artist', 'James Joyce', 1916],
  ['Dubliners', 'James Joyce', 1914],
  ['Mrs Dalloway', 'Virginia Woolf', 1925],
  ['To the Lighthouse', 'Virginia Woolf', 1927],
  ['The Waves', 'Virginia Woolf', 1931],
  ['Heart of Darkness', 'Joseph Conrad', 1899],
  ['Lord of the Flies', 'William Golding', 1954],
  ['The Lord of the Rings', 'J.R.R. Tolkien', 1954],
  ['The Hobbit', 'J.R.R. Tolkien', 1937],
  ['Dune', 'Frank Herbert', 1965],
  ['Neuromancer', 'William Gibson', 1984],
  ['Foundation', 'Isaac Asimov', 1951],
  ['The Left Hand of Darkness', 'Ursula K. Le Guin', 1969],
  ['The Dispossessed', 'Ursula K. Le Guin', 1974],
  ['Kindred', 'Octavia Butler', 1979],
  ['Parable of the Sower', 'Octavia Butler', 1993],
  ['The Handmaid\'s Tale', 'Margaret Atwood', 1985],
  ['Oryx and Crake', 'Margaret Atwood', 2003],
  ['The Road', 'Cormac McCarthy', 2006],
  ['Blood Meridian', 'Cormac McCarthy', 1985],
  ['No Country for Old Men', 'Cormac McCarthy', 2005],
  ['Bel Canto', 'Ann Patchett', 2001],
  ['A Little Life', 'Hanya Yanagihara', 2015],
  ['Normal People', 'Sally Rooney', 2018],
  ['Conversations with Friends', 'Sally Rooney', 2017],
  ['The Goldfinch', 'Donna Tartt', 2013],
  ['The Secret History', 'Donna Tartt', 1992],
  ['Giovanni\'s Room', 'James Baldwin', 1956],
  ['Go Tell It on the Mountain', 'James Baldwin', 1953],
  ['Another Country', 'James Baldwin', 1962],
  ['The Fire Next Time', 'James Baldwin', 1963],
  ['Between the World and Me', 'Ta-Nehisi Coates', 2015],
  ['The Underground Railroad', 'Colson Whitehead', 2016],
  ['The Nickel Boys', 'Colson Whitehead', 2019],
  ['Homegoing', 'Yaa Gyasi', 2016],
  ['The Overstory', 'Richard Powers', 2018],
  ['Station Eleven', 'Emily St. John Mandel', 2014],
  ['Cloud Cuckoo Land', 'Anthony Doerr', 2021],
  ['All the Light We Cannot See', 'Anthony Doerr', 2014],
  ['A Gentleman in Moscow', 'Amor Towles', 2016],
  ['The Remains of the Day', 'Kazuo Ishiguro', 1989],
  ['Never Let Me Go', 'Kazuo Ishiguro', 2005],
  ['Klara and the Sun', 'Kazuo Ishiguro', 2021],
  ['The Buried Giant', 'Kazuo Ishiguro', 2015],
  ['Atonement', 'Ian McEwan', 2001],
  ['Saturday', 'Ian McEwan', 2005],
  ['White Teeth', 'Zadie Smith', 2000],
  ['On Beauty', 'Zadie Smith', 2005],
  ['Swing Time', 'Zadie Smith', 2016],
  ['The Line of Beauty', 'Alan Hollinghurst', 2004],
  ['A Visit from the Goon Squad', 'Jennifer Egan', 2010],
  ['The Corrections', 'Jonathan Franzen', 2001],
  ['Freedom', 'Jonathan Franzen', 2010],
  ['Infinite Jest', 'David Foster Wallace', 1996],
  ['The Pale King', 'David Foster Wallace', 2011],
  ['White Noise', 'Don DeLillo', 1985],
  ['Underworld', 'Don DeLillo', 1997],
  ['Libra', 'Don DeLillo', 1988],
  ['The Recognitions', 'William Gaddis', 1955],
  ['JR', 'William Gaddis', 1975],
  ['Gravity\'s Rainbow', 'Thomas Pynchon', 1973],
  ['The Crying of Lot 49', 'Thomas Pynchon', 1966],
  ['V.', 'Thomas Pynchon', 1963],
  ['Song of Achilles', 'Madeline Miller', 2011],
  ['Circe', 'Madeline Miller', 2018],
  ['The Song of Roland', 'Anonymous', 1100],
  ['Beowulf', 'Anonymous', 1000],
  ['The Canterbury Tales', 'Geoffrey Chaucer', 1400],
  ['Paradise Lost', 'John Milton', 1667],
  ['Frankenstein', 'Mary Shelley', 1818],
  ['Dracula', 'Bram Stoker', 1897],
  ['The Picture of Dorian Gray', 'Oscar Wilde', 1890],
  ['The Importance of Being Earnest', 'Oscar Wilde', 1895],
  ['A Room of One\'s Own', 'Virginia Woolf', 1929],
  ['The Second Sex', 'Simone de Beauvoir', 1949],
  ['The Feminine Mystique', 'Betty Friedan', 1963],
  ['Silent Spring', 'Rachel Carson', 1962],
  ['The Selfish Gene', 'Richard Dawkins', 1976],
  ['Sapiens', 'Yuval Noah Harari', 2011],
  ['Guns, Germs, and Steel', 'Jared Diamond', 1997],
  ['The Sixth Extinction', 'Elizabeth Kolbert', 2014],
  ['Educated', 'Tara Westover', 2018],
  ['When Breath Becomes Air', 'Paul Kalanithi', 2016],
  ['The Year of Magical Thinking', 'Joan Didion', 2005],
  ['Slouching Towards Bethlehem', 'Joan Didion', 1968],
  ['The Argonauts', 'Maggie Nelson', 2015],
  ['Just Kids', 'Patti Smith', 2010],
  ['Wild', 'Cheryl Strayed', 2012],
  ['Into the Wild', 'Jon Krakauer', 1996],
  ['Into Thin Air', 'Jon Krakauer', 1997],
  ['The Immortal Life of Henrietta Lacks', 'Rebecca Skloot', 2010],
  ['Bad Blood', 'John Carreyrou', 2018],
  ['Say Nothing', 'Patrick Radden Keefe', 2018],
  ['The Warmth of Other Suns', 'Isabel Wilkerson', 2010],
  ['Caste', 'Isabel Wilkerson', 2020],
  ['The New Jim Crow', 'Michelle Alexander', 2010],
  ['How to Be an Antiracist', 'Ibram X. Kendi', 2019],
  ['The Autobiography of Malcolm X', 'Malcolm X', 1965],
  ['Long Walk to Freedom', 'Nelson Mandela', 1994],
  ['I Know Why the Caged Bird Sings', 'Maya Angelou', 1969],
  ['The Diary of a Young Girl', 'Anne Frank', 1947],
  ['Man\'s Search for Meaning', 'Viktor Frankl', 1946],
  ['Night', 'Elie Wiesel', 1960],
  ['The Gulag Archipelago', 'Aleksandr Solzhenitsyn', 1973],
  ['One Day in the Life of Ivan Denisovich', 'Aleksandr Solzhenitsyn', 1962],
  ['The Unbearable Lightness of Being', 'Milan Kundera', 1984],
  ['The Book of Laughter and Forgetting', 'Milan Kundera', 1979],
  ['The Trial', 'Franz Kafka', 1925],
  ['The Castle', 'Franz Kafka', 1926],
  ['The Metamorphosis', 'Franz Kafka', 1915],
  ['Steppenwolf', 'Hermann Hesse', 1927],
  ['Siddhartha', 'Hermann Hesse', 1922],
  ['Demian', 'Hermann Hesse', 1919],
  ['The Magic Mountain', 'Thomas Mann', 1924],
  ['Buddenbrooks', 'Thomas Mann', 1901],
  ['Doctor Faustus', 'Thomas Mann', 1947],
  ['The Tin Drum', 'Günter Grass', 1959],
  ['Perfume', 'Patrick Süskind', 1985],
  ['All Quiet on the Western Front', 'Erich Maria Remarque', 1929],
  ['The Reader', 'Bernhard Schlink', 1995],
  ['The Shadow of the Wind', 'Carlos Ruiz Zafón', 2001],
]

const LONDON_AREAS = [
  ['Westminster', 'Westminster Abbey at dawn'],
  ['Westminster', 'Walk through St James\'s Park'],
  ['Westminster', 'Big Ben from Westminster Bridge'],
  ['Westminster', 'Churchill War Rooms'],
  ['Westminster', 'Houses of Parliament tour'],
  ['Westminster', 'Trooping the Colour (June)'],
  ['Westminster', 'Buckingham Palace gates'],
  ['Westminster', 'Changing of the Guard'],
  ['Westminster', 'National Gallery'],
  ['Westminster', 'National Portrait Gallery'],
  ['Westminster', 'Trafalgar Square pigeons (or not)'],
  ['Covent Garden', 'Street performers in the piazza'],
  ['Covent Garden', 'Neal\'s Yard colours'],
  ['Covent Garden', 'Apple Market antiques'],
  ['Covent Garden', 'Royal Opera House foyer'],
  ['Soho', 'Late-night jazz at Ronnie Scott\'s'],
  ['Soho', 'Chinatown dim sum crawl'],
  ['Soho', 'Berwick Street Market'],
  ['Soho', 'Carnaby Street wander'],
  ['Camden', 'Camden Market on a Sunday'],
  ['Camden', 'Regent\'s Canal towpath walk'],
  ['Camden', 'Primrose Hill sunset'],
  ['Camden', 'London Zoo (if you must)'],
  ['Shoreditch', 'Brick Lane curry'],
  ['Shoreditch', 'Columbia Road flower market'],
  ['Shoreditch', 'Street art on Hanbury Street'],
  ['Shoreditch', 'Boxpark rooftop'],
  ['South Bank', 'Walk the entire South Bank'],
  ['South Bank', 'Tate Modern Turbine Hall'],
  ['South Bank', 'Shakespeare\'s Globe'],
  ['South Bank', 'Borough Market Saturday'],
  ['South Bank', 'The Shard view (book ahead)'],
  ['South Bank', 'London Eye at dusk'],
  ['South Bank', 'Hayward Gallery'],
  ['South Bank', 'National Theatre backstage tour'],
  ['Southwark', 'Crossbones Graveyard'],
  ['Southwark', 'The Clink Prison Museum'],
  ['Southwark', 'Maltby Street Market'],
  ['Greenwich', 'Cutty Sark and maritime museum'],
  ['Greenwich', 'Greenwich Park meridian line'],
  ['Greenwich', 'Observatory hill view'],
  ['Greenwich', 'Deptford market'],
  ['East End', 'Wapping old warehouses'],
  ['East End', 'Wilton\'s Music Hall'],
  ['East End', 'Victoria Park boating lake'],
  ['East End', 'Queen Elizabeth Olympic Park'],
  ['North', 'Hampstead Heath swimming ponds'],
  ['North', 'Kenwood House and lake'],
  ['North', 'Highgate Cemetery (east)'],
  ['North', 'Highgate Cemetery (west)'],
  ['North', 'Parliament Hill kite flying'],
  ['North', 'Camden Passage antiques'],
  ['North', 'Alexandra Palace view'],
  ['North', 'Finsbury Park live music'],
  ['West', 'Kew Gardens in spring'],
  ['West', 'Richmond Park deer at dawn'],
  ['West', 'Hampton Court maze'],
  ['West', 'Syon House gardens'],
  ['West', 'Chiswick House'],
  ['West', 'Little Venice canal walk'],
  ['West', 'Portobello Road (Friday)'],
  ['West', 'Notting Hill Carnival (August)'],
  ['West', 'Holland Park Kyoto Garden'],
  ['South', 'Brixton Village food hall'],
  ['South', 'Dulwich Picture Gallery'],
  ['South', 'Crystal Palace dinosaurs'],
  ['South', 'Peckham Levels rooftop'],
  ['South', 'Battersea Power Station'],
  ['South', 'Clapham Common picnic'],
  ['South', 'Tooting Market'],
  ['South', 'Wimbledon Common windmill'],
  ['South', 'Richmond riverside pub'],
  ['City', 'St Paul\'s Cathedral whispering gallery'],
  ['City', 'Sky Garden (free, book ahead)'],
  ['City', 'Leadenhall Market'],
  ['City', 'Museum of London (when it returns)'],
  ['City', 'Barbican conservatory'],
  ['City', 'Postman\'s Park memorials'],
  ['City', 'Smithfield Market early morning'],
  ['City', 'Temple Church'],
  ['City', 'Old Spitalfields Market'],
  ['City', 'Whitechapel Gallery'],
  ['City', 'Tower of London ravens'],
  ['City', 'Tower Bridge walk'],
  ['City', 'Monument climb'],
  ['City', 'St Dunstan in the East ruins'],
  ['Thames', 'Thames Path Hammersmith to Putney'],
  ['Thames', 'Thames Clipper commute'],
  ['Thames', 'Rotherhithe to Canary Wharf walk'],
  ['Thames', 'Thames Barrier'],
  ['Thames', 'Kew to Richmond riverside'],
  ['Hidden', 'Kyoto Garden Holland Park'],
  ['Hidden', 'Leighton House Museum'],
  ['Hidden', 'Sir John Soane\'s Museum'],
  ['Hidden', 'Dennis Severs\' House'],
  ['Hidden', 'Geffrye Museum gardens'],
  ['Hidden', 'Eel Pie Island (open days)'],
  ['Hidden', 'Walthamstow Wetlands'],
  ['Hidden', 'God\'s Own Junkyard neon'],
  ['Hidden', 'House of Dreams (Peckham)'],
  ['Hidden', 'Crossrail Place Roof Garden'],
  ['Seasonal', 'Winter Wonderland (if you dare)'],
  ['Seasonal', 'Kew Christmas lights'],
  ['Seasonal', 'Open House weekend'],
  ['Seasonal', 'Notting Hill Carnival'],
  ['Seasonal', 'Fireworks on the Thames (Nov 5)'],
  ['Seasonal', 'Swimming in Hampstead ponds (summer)'],
  ['Seasonal', 'Open-air cinema (summer)'],
  ['Seasonal', 'Afternoon tea at Claridge\'s'],
  ['Seasonal', 'Pub crawl along the Regent\'s Canal'],
  ['Seasonal', 'Midnight mass at St Paul\'s'],
  ['Seasonal', 'New Year\'s Eve on the Embankment'],
]

function dedupe(raw, keyFn) {
  const seen = new Set()
  const out = []
  for (const row of raw) {
    const k = keyFn(row)
    if (seen.has(k)) continue
    seen.add(k)
    out.push(row)
  }
  return out
}

function slug(s) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
}

const movieBase = {
  time_needed: 'few_hours',
  cost: 'free',
  company: 'any',
  setting: 'home',
  seasons: ['any'],
  topic_tags: ['film'],
}

const movies = dedupe(MOVIE_RAW, (r) => r[0]).slice(0, 100).map(([title, year, director], i) => ({
  key: slug(`${title}-${year}`),
  title,
  subtitle: `${year} · ${director}`,
  meta: { year, director },
  default_tags: { ...movieBase },
  sort_order: i + 1,
}))

const bookBase = {
  time_needed: 'few_hours',
  cost: 'cheap',
  company: 'solo',
  setting: 'home',
  seasons: ['any'],
  topic_tags: ['reading'],
}

const books = dedupe(BOOK_RAW, (r) => r[0]).slice(0, 100).map(([title, author, year], i) => ({
  key: slug(`${title}-${author}`),
  title,
  subtitle: `${author}${year > 0 ? ` · ${year}` : ''}`,
  meta: { author, year },
  default_tags: { ...bookBase },
  sort_order: i + 1,
}))

const londonBase = {
  time_needed: 'few_hours',
  cost: 'cheap',
  company: 'any',
  setting: 'outdoors',
  seasons: ['any'],
  topic_tags: ['london'],
}

const london = LONDON_AREAS.slice(0, 100).map(([area, title], i) => ({
  key: slug(`${area}-${title}`),
  title,
  subtitle: area,
  meta: { area },
  default_tags: { ...londonBase },
  sort_order: i + 1,
}))

function writeModule(name, exportName, items) {
  const body = `const BASE = ${JSON.stringify(items[0]?.default_tags ?? {}, null, 2)}

export const ${exportName} = ${JSON.stringify(items, null, 2).replace(/"default_tags": \{[^}]+\}/g, (m, offset, str) => {
    // keep default_tags as spread reference - actually stringify fully is fine
    return m
  })}
`
  // Fix default_tags to use spread - simpler to just inline full objects
  writeFileSync(join(dir, `${name}.js`), body)
}

writeModule('movies', 'MOVIES', movies)
writeModule('books', 'BOOKS', books)
writeModule('london', 'LONDON', london)

console.log('Generated:', movies.length, 'movies,', books.length, 'books,', london.length, 'london items')
